# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=500)),
                ('kod', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gminy',
                'verbose_name': 'Gmina',
            },
        ),
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Powiaty',
                'verbose_name': 'Powiat',
            },
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Województwa',
                'verbose_name': 'Województwo',
            },
        ),
        migrations.AddField(
            model_name='powiat',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiony.Wojewodztwo'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiony.Powiat'),
        ),
    ]
