# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regiony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=42)),
                ('nazwisko', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kandydaci',
                'verbose_name': 'Kandydat',
            },
        ),
        migrations.CreateModel(
            name='Obwod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.PositiveIntegerField()),
                ('adres', models.CharField(max_length=1000)),
                ('typ', models.CharField(max_length=1)),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiony.Gmina')),
            ],
            options={
                'verbose_name_plural': 'Obwody',
                'verbose_name': 'Obwód',
            },
        ),
        migrations.CreateModel(
            name='Okreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.PositiveIntegerField(unique=True)),
                ('wojewodztwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regiony.Wojewodztwo')),
            ],
            options={
                'verbose_name_plural': 'Okręgi',
                'verbose_name': 'Okręg',
            },
        ),
        migrations.CreateModel(
            name='Statystyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statystyki',
                'verbose_name': 'Statystyka',
            },
        ),
        migrations.CreateModel(
            name='WynikKandydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.PositiveIntegerField()),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.Kandydat')),
                ('obwod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.Obwod')),
            ],
            options={
                'verbose_name_plural': 'Wyniki kandydatów w obwodach',
                'verbose_name': 'Wynik kandydata w obwodzie',
            },
        ),
        migrations.CreateModel(
            name='WynikStatystyki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.PositiveIntegerField()),
                ('obwod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.Obwod')),
                ('statystyka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.Statystyka')),
            ],
            options={
                'verbose_name_plural': 'Wyniki statystyk',
                'verbose_name': 'Wynik statystyki',
            },
        ),
        migrations.AddField(
            model_name='obwod',
            name='okreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.Okreg'),
        ),
        migrations.AlterUniqueTogether(
            name='wynikstatystyki',
            unique_together=set([('statystyka', 'obwod')]),
        ),
        migrations.AlterUniqueTogether(
            name='wynikkandydata',
            unique_together=set([('kandydat', 'obwod')]),
        ),
    ]
